server:
  port: 20000
spring:
  application:
    name: ploufMembres
  data:
    mongodb:
      database: base
      host: localhost
      port: 27017
      username: root
      password: root
      authentication-database: admin

logging:
    level:
      org.springframework.web: INFO

